ahmedkhd_sylius_paymob_plugin_notify_url:
  path: /payment/paymob/capture
  methods: [GET]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:doAction

hyper_pay_Action:
  path: /payment/hyperpay/capture
  methods: [GET]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:hyperpayAction

hyper_pay_webhook_Action:
  path: /payment/hyperpay/webhook
  methods: [POST]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:hyperpayWebhookAction


ahmedkhd_sylius_paymob_plugin_notify_url_webhook:
  path: /payment/paymob/webhook
  methods: [POST]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:webhookAction


hyperpay:
  path: /hyperpay
  methods: [GET]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:hyperpay


webhook:
  path: /payment/webhook
  methods: [post]
  defaults:
    _controller: Ahmedkhd\SyliusPaymobPlugin\Controller\NotifyController:webhook


